name: ask_quotation_customer
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.0.0
  modal_progress_hud: ^0.1.3
  font_awesome_flutter:
  url_launcher: ^5.6.0
  fluttertoast: ^8.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  assets:
    - images/

  fonts:
    - family: Circular
      fonts:
        - asset: fonts/CircularStd-Medium.ttf
        - asset: fonts/CircularAir-Light.ttf
          weight: 100
        - asset: fonts/CircularStd-Bold.ttf
          weight: 500